---
title: Constellation
---
erDiagram
    %% Constellation
    constellation {
        uuid id PK
        text name UK
        text iau
        text nasa
        text genitive
        text pronunciation_name
        text pronunciation_genitive
        text symbolism
        text origin
        text note
    }
